
import { ProgressIndicator, Spinner, Slider, Switch, ListView, GroupBox } from "std-widgets.slint";
import { MenuItem } from "menu_item.slint";
import { SettingsPage } from "pages/settings.slint";
import { MenuPage } from "menu.slint";

export component RsWatchUi inherits Window {
    callback menu_item_click(int);
    callback brightness_setting_changed <=> settings-page.brightness_changed;
    height: 240px;
    width: 240px;
    property <int> selected-page: 0;
    Rectangle {
        background: white;
        border-width: 1px;
        border-color: #ff0fd7;
        border-radius: root.height / 2;
        // Menu page
        menu-page := MenuPage {
            active: selected-page == 0;
            menu-item-click(i) => {
                if i <= 1 {
                    selected-page = i;
                }
                menu_item_click(i);
            }
        }

        // Seettings page
        settings-page := SettingsPage {
            active: selected-page == 1;
            back => {
                selected-page = 0;
            }
        }
    }
}
