import { MenuItem } from "menu_item.slint";

export component MenuPage inherits Flickable {
    callback menu-item-click(int);
    in property <bool> active: false;
    states [
        shown when active: {
            x: 0px;
            in {
                animate x {
                    duration: 500ms;
                    easing: ease-in-expo;
                }
            }
            out {
                animate x {
                    duration: 500ms;
                    easing: ease-out-expo;
                }
            }
        }
        hidden when !active: {
            x: -240px;
        }
    ]
    property <length> icon_size: 32px; // This has currently to match the SVG size :'(
    property <length> items_spacing: 12px;
    vertical-stretch: 0;
    viewport-x: 0px;
    viewport-y: 0px;
    VerticalLayout {
        padding-left: 30px;
        padding-top: 40px;
        padding-bottom: self.padding-top;
        spacing: items_spacing;
        alignment: start;
        MenuItem {
            title: "Settings";
            icon: @image-url("../images/icon_settings.svg");
            icon_size: icon_size;
            clicked => {
                menu-item-click(1);
            }
        }

        MenuItem {
            title: "Home";
            icon: @image-url("../images/icon_home.svg");
            icon_size: icon_size;
            clicked => {
                menu-item-click(2);
            }
        }

        MenuItem {
            title: "Timer";
            icon: @image-url("../images/icon_timer.svg");
            icon_size: icon_size;
            clicked => {
                menu-item-click(3);
            }
        }

        MenuItem {
            title: "Media";
            icon: @image-url("../images/icon_media.svg");
            icon_size: icon_size;
            clicked => {
                menu-item-click(4);
            }
        }

        MenuItem {
            title: "Lock";
            icon: @image-url("../images/icon_lock.svg");
            icon_size: icon_size;
            clicked => {
                menu-item-click(5);
            }
        }

        MenuItem {
            title: "Bluetooth ®";
            icon: @image-url("../images/icon_bluetooth_settings.svg");
            icon_size: icon_size;
            clicked => {
                menu-item-click(6);
            }
        }

        MenuItem {
            title: "Alarm";
            icon: @image-url("../images/icon_alarm.svg");
            icon_size: icon_size;
            clicked => {
                menu-item-click(7);
            }
        }
    }
}
